config/routes.rb
Fileshare::Application.routes.draw do
match "browse/:folder_id" => "home#browse", :as => "browse"
  resources :folders

  resources :assets

  devise_for :users
  root :to => "home#index"

match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"

match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"

match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"

match "home/share" => "home#share"

match "assets/get/:id" => "assets#get", :as => "download"

end

app/models/folder.rb
class Folder < ActiveRecord::Base
  acts_as_tree
  belongs_to :user
  has_many :assets, :dependent => :destroy
  has_many :shared_folders, :dependent => :destroy
  attr_accessible :name, :parent_id, :user_id

  #a method to check if a folder has been shared or not
def shared?
    !self.shared_assets.empty?
end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @folders = current_user.folders
  end

  def show
    @folder = current_user.folders.find(params[:id])
  end

  def new
   @folder = current_user.folders.new
   #if there is "folder_id" param, we know that we are under a folder, thus, we will essentially create a subfolder
   if params[:folder_id] #if we want to create a folder inside another folder

     #we still need to set the @current_folder to make the buttons working fine
     @current_folder = current_user.folders.find(params[:folder_id])

     #then we make sure the folder we are creating has a parent folder which is the @current_folder
     @folder.parent_id = @current_folder.id
   end
end

  def create
   @folder = current_user.folders.new(params[:folder])
   if @folder.save
    flash[:notice] = "Successfully created folder."

    if @folder.parent #checking if we have a parent folder on this one
      redirect_to browse_path(@folder.parent)  #then we redirect to the parent folder
    else
      redirect_to root_url #if not, redirect back to home page
    end
   else
    render :action => 'new'
   end
end

  def edit
    @folder = current_user.folders.find(params[:folder_id])
    @current_folder = @folder.parent    #this is just for breadcrumbs
end

  def update
    @folder = current_user.folders.find(params[:id])
    if @folder.update_attributes(params[:folder])
      redirect_to @folder, :notice  => "Successfully updated folder."
    else
      render :action => 'edit'
    end
  end

  def destroy
   @folder = current_user.folders.find(params[:id])
   @parent_folder = @folder.parent #grabbing the parent folder

   #this will destroy the folder along with all the contents inside
   #sub folders will also be deleted too as well as all files inside
   @folder.destroy
   flash[:notice] = "Successfully deleted the folder and all the contents inside."

   #redirect to a relevant path depending on the parent folder
   if @parent_folder
    redirect_to browse_path(@parent_folder)
   else
    redirect_to root_url
   end
end
end

app/helpers/folders_helper.rb
module FoldersHelper
end

app/views/folders/_form.html.erb
<%= form_for @folder do |f| %>
 <%= f.error_messages %>
 <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
 </p>
   <%= f.hidden_field :parent_id %>
 <p>
<% if @folder.new_record? %>
   <%= f.submit "Create Folder" %>
<% else %>
   <%= f.submit "Rename Folder" %>
<% end %>
</p>
<% end %>

app/views/folders/edit.html.erb
<% title "Rename Folder" %>
<%= render :partial => "home/breadcrumbs" %>

<%= render 'form' %>

<p>
<% if @folder.parent %>
   <%= link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent) %>
<% else %>
   <%= link_to "Back", root_url %>
<% end %>
</p>

app/views/folders/index.html.erb
<% title "Folders" %>

<table>
  <tr>
    <th>Name</th>
    <th>Parent</th>
    <th>User</th>
  </tr>
  <% for folder in @folders %>
    <tr>
      <td><%= folder.name %></td>
      <td><%= folder.parent_id %></td>
      <td><%= folder.user_id %></td>
      <td><%= link_to "Show", folder %></td>
      <td><%= link_to "Edit", edit_folder_path(folder) %></td>
      <td><%= link_to "Destroy", folder, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Folder", new_folder_path %></p>

app/views/folders/new.html.erb
<% title "New Folder" %>
<%= render :partial => "home/breadcrumbs" %>
<%= render 'form' %>

<p>
<% if @folder.parent %>
   <%= link_to "Back to '#{@folder.parent.name}' Folder", browse_path(@folder.parent) %>
<% else %>
   <%= link_to "Back to Home page", root_url %>
<% end %>
</p>

app/views/folders/show.html.erb
<% title "Folder" %>

<p>
  <strong>Name:</strong>
  <%= @folder.name %>
</p>
<p>
  <strong>Parent:</strong>
  <%= @folder.parent_id %>
</p>
<p>
  <strong>User:</strong>
  <%= @folder.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_folder_path(@folder) %> |
  <%= link_to "Destroy", @folder, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", folders_path %>
</p>