config/routes.rb
Fileshare::Application.routes.draw do
match "browse/:folder_id" => "home#browse", :as => "browse"
  resources :folders

  resources :assets

  devise_for :users
  root :to => "home#index"

match "browse/:folder_id/new_folder" => "folders#new", :as => "new_sub_folder"

match "browse/:folder_id/new_file" => "assets#new", :as => "new_sub_file"

match "browse/:folder_id/rename" => "folders#edit", :as => "rename_folder"

match "home/share" => "home#share"

match "assets/get/:id" => "assets#get", :as => "download"

end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessible :user_id
  belongs_to :user
  attr_accessible :user_id, :uploaded_file
  attr_accessible :user_id, :uploaded_file, :folder_id
  belongs_to :folder

#set up "uploaded_file" field as attached_file (using Paperclip)
  has_attached_file :uploaded_file,{
  :path => "assets/:id/:basename.:extension"
}.merge(PAPERCLIP_STORAGE_OPTIONS)


validates_attachment_size :uploaded_file, :less_than => 10.megabytes
validates_attachment_presence :uploaded_file
  def file_name
    uploaded_file_file_name
end

def file_size
    uploaded_file_file_size
end
end

app/controllers/assets_controller.rb
require 'open-uri'
class AssetsController < ApplicationController
  before_filter :authenticate_user!  #authenticate for users before any methods is called


  def index
    @assets = current_user.assets
  end

  def show
    @asset = current_user.assets.find(params[:id])
  end

  def new
  @asset = current_user.assets.build
  if params[:folder_id] #if we want to upload a file inside another folder
   @current_folder = current_user.folders.find(params[:folder_id])
   @asset.folder_id = @current_folder.id
  end
end

  def create
  @asset = current_user.assets.build(params[:asset])
  if @asset.save
   flash[:notice] = "Successfully uploaded the file."

   if @asset.folder #checking if we have a parent folder for this file
     redirect_to browse_path(@asset.folder)  #then we redirect to the parent folder
   else
     redirect_to root_url
   end
  else
   render :action => 'new'
  end
end

  def edit
    @asset = current_user.assets.find(params[:id])
  end

  def update
    @asset = current_user.assets.find(params[:id])
    if @asset.update_attributes(params[:asset])
      redirect_to @asset, :notice  => "Successfully updated asset."
    else
      render :action => 'edit'
    end
  end

  def destroy
  @asset = current_user.assets.find(params[:id])
  @parent_folder = @asset.folder #grabbing the parent folder before deleting the record
  @asset.destroy
  flash[:notice] = "Successfully deleted the file."

  #redirect to a relevant path depending on the parent folder
  if @parent_folder
   redirect_to browse_path(@parent_folder)
  else
   redirect_to root_url
  end
end

  def get
  asset = current_user.assets.find_by_id(params[:id])

  #if not found in own assets, check if the current_user has share access to the parent folder of the File
 asset ||= Asset.find(params[:id]) if current_user.has_share_access?(Asset.find_by_id(params[:id]).folder) 

  if asset
    #Parse the URL for special characters first before downloading
    data = open(URI.parse(URI.encode(asset.uploaded_file.url)))

    #then again, use the "send_data" method to send the above binary "data" as file.
    send_data data, :filename => asset.uploaded_file_file_name

    #redirect to amazon S3 url which will let the user download the file automatically
    #redirect_to asset.uploaded_file.url, :type => asset.uploaded_file_content_type
  else
    flash[:error] = "Don't be cheeky! Mind your own assets!"
    redirect_to root_url
  end
end

end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_form.html.erb
<%= form_for @asset, :html => {:multipart => true} do |f| %>
  <%= f.error_messages %>
    <p>
        <%= f.label :uploaded_file, "File" %><br />
        <%= f.file_field :uploaded_file %>
      </p>
  <%= f.hidden_field :folder_id %>
  <p><%= f.submit "Upload" %></p>
<% end %>

app/views/assets/edit.html.erb
<% title "Edit Asset" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @asset %> |
  <%= link_to "View All", assets_path %>
</p>

app/views/assets/index.html.erb
<% title "Assets" %>

<table>
  <tr>
    <th>uploaded files</th>
  </tr>
  <% for asset in @assets %>
    <tr>
      <td><%= link_to asset.uploaded_file_file_name, asset.uploaded_file.url %></td>
      <td><%= link_to "Show", asset %></td>
      <td><%= link_to "Edit", edit_asset_path(asset) %></td>
      <td><%= link_to "Destroy", asset, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Asset", new_asset_path %></p>

app/views/assets/new.html.erb
<% title "Upload a file" %>
<%= render :partial => "home/breadcrumbs" %>

<%= render 'form' %>

<p>
<% if @asset.folder %>
   <%= link_to "Back to '#{@asset.folder.name}' Folder", browse_path(@asset.folder) %>
<% else %>
   <%= link_to "Back", root_url %>
<% end %>
</p>

app/views/assets/show.html.erb
<% title "Asset" %>

<p>
  <strong>User:</strong>
  <%= @asset.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_asset_path(@asset) %> |
  <%= link_to "Destroy", @asset, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", assets_path %>
</p>